Shop/Models/RealEstate/ImageToDatabaseViewModel.cs
namespace Shop.Models.Realestate
{
    public class ImageToDatabaseViewModel
    {
        public Guid ImageId { get; set; }
        public string ImageTitle { get; set; }
        public byte[] ImageData { get; set; }
        public string Image { get; set; }
        public Guid? RealEstateId { get; set; }
    }
}

Shop/Models/RealEstate/RealEstateCreateUpdateViewModel.cs
namespace Shop.Models.Realestate
{
    public class RealestateCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string Address { get; set; }
        public float SizeSqrM { get; set; }
        public int RoomCount { get; set; }
        public int Floor { get; set; }
        public string BuildingType { get; set; }
        public DateTime BuiltInYear { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }

        public List<IFormFile> Files { get; set; }
        public List<ImageToDatabaseViewModel> Image { get; set; } = new List<ImageToDatabaseViewModel>();
    }
}

Shop/Models/RealEstate/RealEstateDeleteViewModel.cs
namespace Shop.Models.Realestate
{
    public class RealEstateDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string Address { get; set; }
        public float SizeSqrM { get; set; }
        public int RoomCount { get; set; }
        public int Floor { get; set; }
        public string BuildingType { get; set; }
        public DateTime BuiltInYear { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }

        public List<ImageToDatabaseViewModel> ImageToDatabase { get; set; } = new List<ImageToDatabaseViewModel>();
    }
}

Shop/Models/RealEstate/RealEstateDetailsViewModel.cs
namespace Shop.Models.Realestate
{
    public class RealEstateDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string Address { get; set; }
        public float SizeSqrM { get; set; }
        public int RoomCount { get; set; }
        public int Floor { get; set; }
        public string BuildingType { get; set; }
        public DateTime BuiltInYear { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }

        public List<ImageToDatabaseViewModel> Image { get; set; } = new List<ImageToDatabaseViewModel>();
    }
}

Shop/Models/RealEstate/RealEstateIndexViewModel.cs
namespace Shop.Models.Realestate
{
    public class RealEstateIndexViewModel
    {
        public Guid? Id { get; set; }
        public string Address { get; set; }
        public float SizeSqrM { get; set; }
        public int RoomCount { get; set; }
        public int Floor { get; set; }
        public string BuildingType { get; set; }
        public DateTime BuiltInYear { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

Shop/Controllers/RealEstatesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shop.ApplicationServices.Services;
using Shop.Core.Dto;
using Shop.Core.ServiceInterface;
using Shop.Data;
using Shop.Models.Realestate;

namespace Shop.Controllers
{
    public class RealEstateController : Controller
    {
        private readonly ShopContext _context;
        private readonly IRealEstateServices _realEstateServices;
        private readonly IFileServices _fileServices;

        public RealEstateController(ShopContext context, IRealEstateServices realEstateServices, IFileServices fileServices)
        {
            _context = context;
            _realEstateServices = realEstateServices;
            _fileServices = fileServices;
        }

        public IActionResult Index()
        {
            var result = _context.RealEstates
                .Select(x => new RealEstateIndexViewModel
                {
                    Id = x.Id,
                    Address = x.Address,
                    SizeSqrM = x.SizeSqrM,
                    RoomCount = x.RoomCount,
                    Floor = x.Floor,
                    BuildingType = x.BuildingType,
                    BuiltInYear = x.BuiltInYear,
                });

            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            RealestateCreateUpdateViewModel realEstate = new RealestateCreateUpdateViewModel();

            return View("CreateUpdate", realEstate);
        }

        [HttpPost]
        public async Task<IActionResult> Create(RealestateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Address = vm.Address,
                SizeSqrM = vm.SizeSqrM,
                RoomCount = vm.RoomCount,
                Floor = vm.Floor,
                BuildingType = vm.BuildingType,
                BuiltInYear = vm.BuiltInYear,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
                Files = vm.Files,
                Image = vm.Image.Select(x => new FileToDatabaseDto
                {
                    Id = x.ImageId,
                    ImageData = x.ImageData,
                    ImageTitle = x.ImageTitle,
                    RealEstateId = x.RealEstateId
                }).ToArray()
            };

            var result = await _realEstateServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var realEstate = await _realEstateServices.GetAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            var photos = await _context.FileToDatabases
                .Where(x => x.RealEstateId == id)
                .Select(y => new ImageToDatabaseViewModel
                {
                    RealEstateId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new RealEstateDetailsViewModel();

            vm.Id = realEstate.Id;
            vm.Address = realEstate.Address;
            vm.SizeSqrM = realEstate.SizeSqrM;
            vm.RoomCount = realEstate.RoomCount;
            vm.Floor = realEstate.Floor;
            vm.BuildingType = realEstate.BuildingType;
            vm.BuiltInYear = realEstate.BuiltInYear;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.UpdatedAt = realEstate.UpdatedAt;
            vm.Image.AddRange(photos);

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var realEstate = await _realEstateServices.GetAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            var photos = await _context.FileToDatabases
                .Where(x => x.RealEstateId == id)
                .Select(y => new ImageToDatabaseViewModel
                {
                    RealEstateId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64, {0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new RealestateCreateUpdateViewModel();

            vm.Id = realEstate.Id;
            vm.Address = realEstate.Address;
            vm.SizeSqrM = realEstate.SizeSqrM;
            vm.RoomCount = realEstate.RoomCount;
            vm.Floor = realEstate.Floor;
            vm.BuildingType = realEstate.BuildingType;
            vm.BuiltInYear = realEstate.BuiltInYear;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.UpdatedAt = realEstate.UpdatedAt;
            vm.Image.AddRange(photos);

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(RealestateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Address = vm.Address,
                SizeSqrM = vm.SizeSqrM,
                RoomCount = vm.RoomCount,
                Floor = vm.Floor,
                BuildingType = vm.BuildingType,
                BuiltInYear = vm.BuiltInYear,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
                Files = vm.Files,
                Image = vm.Image.Select(x => new FileToDatabaseDto
                {
                    Id = x.ImageId,
                    ImageData = x.ImageData,
                    ImageTitle = x.ImageTitle,
                    RealEstateId = x.RealEstateId,
                }).ToArray()
            };

            var result = await _realEstateServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var realEstate = await _realEstateServices.GetAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            var photos = await _context.FileToDatabases
                .Where(x => x.RealEstateId == id)
                .Select(y => new ImageToDatabaseViewModel
                {
                    RealEstateId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new RealEstateDeleteViewModel();

            vm.Id = realEstate.Id;
            vm.Address = realEstate.Address;
            vm.SizeSqrM = realEstate.SizeSqrM;
            vm.RoomCount = realEstate.RoomCount;
            vm.Floor = realEstate.Floor;
            vm.BuildingType = realEstate.BuildingType;
            vm.BuiltInYear = realEstate.BuiltInYear;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.UpdatedAt = realEstate.UpdatedAt;
            vm.ImageToDatabase.AddRange(photos);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var realEstateId = await _realEstateServices.Delete(id);

            if (realEstateId == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveImage(ImageToDatabaseViewModel file)
        {
            var dto = new FileToDatabaseDto()
            {
                Id = file.ImageId
            };

            var image = await _fileServices.RemoveImageFromDatabase(dto);

            if (image == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveImages(ImageToDatabaseViewModel[] files)
        {
            foreach (var file in files)
            {
                var dto = new FileToDatabaseDto()
                {
                    Id = file.ImageId
                };

                var image = await _fileServices.RemoveImageFromDatabase(dto);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Shop/Views/RealEstate/CreateUpdate.cshtml
@model Shop.Models.Realestate.RealestateCreateUpdateViewModel

@@if (Model.Id.HasValue)
{
<h1>Update</h1>
}
else
{
<h1>Create</h1>
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Address" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Address" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="SizeSqrM" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="SizeSqrM" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="RoomCount" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="RoomCount" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Floor" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Floor" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="BuildingType" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BuiltInYear" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="BuiltInYear" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Files" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-5">
                <div class="custom-file">
                    <input class="form-control custom-file-label" asp-for="Files" multiple type="file" />
                    <label class="custom-file-label">Choose File...</label>
                </div>
            </div>
        </div>

        @foreach (var images in Model.Image)
        {
            <partial name="_Images" model="images" />
            <input asp-action="removeImage" asp-controller="realestate" asp-route-imageId="@images.ImageId" 
            type="submit" class="btn btn-danger" value="Remove Image" />
        }

        <hr />

        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="realestate" type="submit" class="btn btn-primary" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="realestate" type="submit" class="btn btn-primary" value="Create" />
        }

        <a asp-action="index" class="btn btn-primary">Index</a>

    </form>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileLabel = $(this).next('.custom-file-label');
                var files = $(this)[0].files;
                if (files.length > 1) {
                    fileLabel.html(files.length + ' files selected');
                }
                else if (files.length == 1) {
                    fileLabel.html(files[0].name);
                }
            });
        });
    </script>
}

Shop/Views/RealEstate/Delete.cshtml
@model Shop.Models.Realestate.RealEstateDeleteViewModel

<h1>Delete</h1>

<div>
    <h4>Real Estate</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Address" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Address)
        </div>

        <div class="form-group row">
            <label asp-for="SizeSqrM" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.SizeSqrM)
        </div>

        <div class="form-group row">
            <label asp-for="RoomCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.RoomCount)
        </div>

        <div class="form-group row">
            <label asp-for="Floor" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Floor)
        </div>

        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.BuildingType)
        </div>

        <div class="form-group row">
            <label asp-for="BuiltInYear" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.BuiltInYear)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.UpdatedAt)
        </div>

        @foreach (var images in Model.ImageToDatabase)
        {
            <partial name="_Images" model="images" />
        }

    </dl>
    <hr />
    <form asp-action="DeleteConfirmation">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="index" class="btn btn-primary">Index</a>
    </form>
</div>

Shop/Views/RealEstate/Details.cshtml
@model Shop.Models.Realestate.RealEstateDetailsViewModel

<h1>Details</h1>

<div>
    <h4>Real Estate</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Address" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Address)
        </div>

        <div class="form-group row">
            <label asp-for="SizeSqrM" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.SizeSqrM)
        </div>

        <div class="form-group row">
            <label asp-for="RoomCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.RoomCount)
        </div>

        <div class="form-group row">
            <label asp-for="Floor" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Floor)
        </div>

        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.BuildingType)
        </div>

        <div class="form-group row">
            <label asp-for="BuiltInYear" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.BuiltInYear)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.UpdatedAt)
        </div>

        @foreach (var images in Model.Image)
        {
            <partial name="_Images" model="images" />
        }

    </dl>
    <hr />
    <a asp-action="index" class="btn btn-primary">Index</a>
</div>

Shop/Views/RealEstate/Images.cshtml
@model Shop.Models.Realestate.ImageToDatabaseViewModel

@{
    var photoPath = $"data:image/gif;base64,{Convert.ToBase64String(Model.ImageData)}";
}

<div class="form btn-group row col-sm-4 offset-2">
    <div>@Model.ImageTitle</div>
    <img class="card-img-top" src="@photoPath" asp-append-version="true" />
</div>

Shop/Views/RealEstate/Index.cshtml
@model IEnumerable<Shop.Models.Realestate.RealEstateIndexViewModel>

<div class="h1">
    Real Estates
</div>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="RealEstate" class="btn btn-primary">Create</a>
</div>

<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Address</th>
                <th scope="col">SizeSqrtM</th>
                <th scope="col">RoomCount</th>
                <th scope="col">Floor</th>
                <th scope="col">BuildingType</th>
                <th scope="col">Built In Year</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var realEstate in Model)
                {
                    var year = realEstate.BuiltInYear.ToShortDateString();

                    <tr>
                        <td>@(rowNumber++)</td>
                        <td>@realEstate.Address</td>
                        <td>@realEstate.SizeSqrM</td>
                        <td>@realEstate.RoomCount</td>
                        <td>@realEstate.Floor</td>
                        <td>@realEstate.BuildingType</td>
                        <td>@year</td>
                        <td>
                            <a asp-action="details" asp-controller="realestate" asp-route-id="@realEstate.Id" class="btn btn-info">Details</a>
                            <a asp-action="update" asp-controller="realestate" asp-route-id="@realEstate.Id" class="btn btn-outline-primary">Update</a>
                            <a asp-action="delete" asp-controller="realestate" asp-route-id="@realEstate.Id" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>

</form>

Shop/Views/RealEstate/_Images.cshtml
@model Shop.Models.Realestate.ImageToDatabaseViewModel

<div class="form-group row col-sm-4 offset-2">
    <div>@Model.ImageTitle</div>
    <img class="card-img-top" src="@Model.Image" asp-append-version="true" />
</div>